[pytest]
addopts =
    -v
    --browser=chromium
    --headed
    --base-url=http://localhost/opencart

    # ------------------------------
    # Debug options
    # ------------------------------
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure

    # ------------------------------
    # Reports
    # ------------------------------
    --html=reports/myreport.html --self-contained-html --capture=tee-sys
    --alluredir=reports/allure-results
    #------parallel-----------
    -n = 2
    --numprocesses=2
    # ------------------------------
    #-m "sanity"
    #-m "regression"
    #-m "sanity and regression"
markers =
    sanity
    regression
    smoke
